### ISSUE TITLE
Add ability to download images

### ISSUE THREAD

**Issue by wogam** [wogam/image-gallery-comfyui#12]
So remote users stop yapping in my ear about it

**Comment by DadoIrie** [comment]
those remote users don't know about *right click* & *save image as* ... really?!? this feature is a complete waste of time if you ask me

**Comment by wogam** [comment]
> those remote users don't know about _right click_ & _save image as_ ... really?!? this feature is a complete waste of time if you ask me

It's for touch/iPad users. The whole UI was made for iPad use so you can generate -> export to lightroom/procreate/etc
