### ISSUE TITLE
Gallery button not appearing on old UI

### ISSUE THREAD

**Issue by tbcarver** [wogam/image-gallery-comfyui#15]
I get the console message that couldn't find the clear workflow button.  I did get it to load at the bottom of the normal list of buttons by doing a const lastButton = document.querySelector('div.comfy-menu > button:last-of-type');  This worked well.  Also for some reason the View Gallery wasn't shows on the button just the image.  the Inner text needs to be the svg and the image text, not just the title.

**Comment by tbcarver** [comment]
I fixed this and made a pull request.  Please approve and merge.  Thanks!

**Comment by wogam** [comment]
#16
