### ISSUE TITLE
'list' object has no attribute 'items'

### ISSUE THREAD

**Issue by tbcarver** [wogam/image-gallery-comfyui#8]
Traceback (most recent call last):
  File "C:\Users\tbcar\Apps\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2001, in load_custom_node
    for name, node_cls in module.NODE_CLASS_MAPPINGS.items():
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'items'

Cannot import C:\Users\tbcar\Apps\ComfyUI_windows_portable\ComfyUI\custom_nodes\image-gallery-comfyui module for custom nodes: 'list' object has no attribute 'items'

This is on first load.  This has happened on 2 separate installs, both windows and linux.

**Comment by DadoIrie** [comment]
fixed with https://github.com/wogam/image-gallery-comfyui/pull/1 and other things like the missing gallery button on the comfyui menu - @wogam did not merge the pr yet

**Comment by wogam** [comment]
The commit b333f6f fixed it
